// f4-data/src/auxaero_rosetta.cpp
//
// GENERATED FILE — do not edit by hand.
// Source: f4-convert/rosetta/auxaero_field_map.json
// Regenerate with: python3 scripts/gen_auxaero_table.py

#include "f4/data/auxaero_rosetta.hpp"

namespace f4::data {

const RosettaEntry kAuxAeroRosetta[kAuxAeroRosettaCount] = {
    {"normSpoolRate", RosettaType::Float, "normSpoolRate", "0.7"},
    {"abSpoolRate", RosettaType::Float, "abSpoolRate", "0.4"},
    {"jfsSpoolUpRate", RosettaType::Float, "jfsSpoolUpRate", "15"},
    {"jfsSpoolUpLimit", RosettaType::Float, "jfsSpoolUpLimit", "0.25"},
    {"lightupSpoolRate", RosettaType::Float, "lightupSpoolRate", "10"},
    {"flameoutSpoolRate", RosettaType::Float, "flameoutSpoolRate", "5"},
    {"jfsRechargeTime", RosettaType::Float, "jfsRechargeTime", "60"},
    {"jfsMinRechargeRpm", RosettaType::Float, "jfsMinRechargeRpm", "0.12"},
    {"jfsSpinTime", RosettaType::Float, "jfsSpinTime", "240"},
    {"mainGenRpm", RosettaType::Float, "mainGenRpm", "0.63"},
    {"stbyGenRpm", RosettaType::Float, "stbyGenRpm", "0.6"},
    {"epuBurnTime", RosettaType::Float, "epuBurnTime", "600"},
    {"DeepStallEngineStall", RosettaType::Int, "DeepStallEngineStall", "0"},
    {"engineDamageStopThreshold", RosettaType::Int, "engineDamageStopThreshold", "13"},
    {"engineDamageNoRestartThreshold", RosettaType::Int, "engineDamageNoRestartThreshold", "50"},
    {"engineDamageHitThreshold", RosettaType::Int, "engineDamageHitThreshold", "0"},
    {"rollMomentum", RosettaType::Float, "rollMomentum", "1"},
    {"pitchMomentum", RosettaType::Float, "pitchMomentum", "1"},
    {"yawMomentum", RosettaType::Float, "yawMomentum", "1"},
    {"pitchElasticity", RosettaType::Float, "pitchElasticity", "1"},
    {"gearPitchFactor", RosettaType::Float, "gearPitchFactor", "0.1"},
    {"rollGearGain", RosettaType::Float, "rollGearGain", "0.6"},
    {"yawGearGain", RosettaType::Float, "yawGearGain", "0.6"},
    {"pitchGearGain", RosettaType::Float, "pitchGearGain", "0.8"},
    {"sinkRate", RosettaType::Float, "sinkRate", "15"},
    {"tefMaxAngle", RosettaType::Float, "tefMaxAngle", "20"},
    {"hasFlapperons", RosettaType::Int, "hasFlapperons", "1"},
    {"hasTef", RosettaType::Int, "hasTef", "2"},
    {"CLtefFactor", RosettaType::Float, "CLtefFactor", "0.05"},
    {"CDtefFactor", RosettaType::Float, "CDtefFactor", "0.05"},
    {"tefNStages", RosettaType::Int, "tefNStages", "2"},
    {"tefTakeoff", RosettaType::Float, "tefTakeOff", "0"},
    {"tefRate", RosettaType::Float, "tefRate", "5"},
    {"lefRate", RosettaType::Float, "lefRate", "5"},
    {"hasLef", RosettaType::Int, "hasLef", "2"},
    {"lefGround", RosettaType::Float, "lefGround", "-2"},
    {"lefMaxAngle", RosettaType::Float, "lefMaxAngle", "20"},
    {"lefMaxMach", RosettaType::Float, "lefMaxMach", "0.4"},
    {"lefNStages", RosettaType::Int, "lefNStages", "1"},
    {"CDlefFactor", RosettaType::Float, "CDlefFactor", "0.0"},
    {"CDSPDBFactor", RosettaType::Float, "CDSPDBFactor", "0.08"},
    {"CDLDGFactor", RosettaType::Float, "CDLDGFactor", "0.06"},
    {"flapGearRelative", RosettaType::Int, "flapGearRelative", "1"},
    {"maxFlapVcas", RosettaType::Float, "maxFlapVcas", "370"},
    {"flapVcasRange", RosettaType::Float, "flapVcasRange", "130"},
    {"area2Span", RosettaType::Float, "area2Span", "0.1066"},
    {"rudderMaxAngle", RosettaType::Float, "rudderMaxAngle", "20"},
    {"aileronMaxAngle", RosettaType::Float, "aileronMaxAngle", "20"},
    {"elevonMaxAngle", RosettaType::Float, "elevonMaxAngle", "20"},
    {"airbrakeMaxAngle", RosettaType::Float, "airbrakeMaxAngle", "60"},
    {"hasSwingWing", RosettaType::Int, "hasSwingWing", "0"},
    {"isComplex", RosettaType::Int, "isComplex", "0"},
    {"landingAOA", RosettaType::Float, "landingAOA", "12.5"},
    {"dragChuteCd", RosettaType::Float, "dragChuteCd", "0"},
    {"dragChuteMaxSpeed", RosettaType::Float, "dragChuteMaxSpeed", "170"},
    {"rollCouple", RosettaType::Float, "rollCouple", "0"},
    {"elevatorRoll", RosettaType::Int, "elevatorRolls", "1"},
    {"canopyMaxAngle", RosettaType::Float, "canopyMaxAngle", "20"},
    {"canopyRate", RosettaType::Float, "canopyRate", "5"},
    {"fuelFlowFactorNormal", RosettaType::Float, "fuelFlowFactorNormal", "0.25"},
    {"fuelFlowFactorAb", RosettaType::Float, "fuelFlowFactorAb", "0.65"},
    {"minFuelFlow", RosettaType::Float, "minFuelFlow", "1200"},
    {"fuelFwdRes", RosettaType::Float, "fuelFwdRes", "0"},
    {"fuelAftRes", RosettaType::Float, "fuelAftRes", "0"},
    {"fuelFwd1", RosettaType::Float, "fuelFwd1", "0"},
    {"fuelAft1", RosettaType::Float, "fuelAft1", "0"},
    {"fuelWingAl", RosettaType::Float, "fuelWingAl", "0"},
    {"fuelWingFr", RosettaType::Float, "fuelWingFr", "0"},
    {"fuelFwdResRate", RosettaType::Float, "fuelFwdResRate", "0"},
    {"fuelAftResRate", RosettaType::Float, "fuelAftResRate", "0"},
    {"fuelFwd1Rate", RosettaType::Float, "fuelFwd1Rate", "0"},
    {"fuelAft1Rate", RosettaType::Float, "fuelAft1Rate", "0"},
    {"fuelWingAlRate", RosettaType::Float, "fuelWingAlRate", "0"},
    {"fuelWingFrRate", RosettaType::Float, "fuelWingFrRate", "0"},
    {"fuelClineRate", RosettaType::Float, "fuelClineRate", "0"},
    {"fuelWingExtRate", RosettaType::Float, "fuelWingExtRate", "0"},
    {"fuelMinFwd", RosettaType::Float, "fuelMinFwd", "400"},
    {"fuelMinAft", RosettaType::Float, "fuelMinAft", "250"},
    {"nChaff", RosettaType::Int, "nChaff", "60"},
    {"nFlare", RosettaType::Int, "nFlare", "30"},
    {"gunLocation", RosettaType::Vector, "gunLocation", "2 -2 0"},
    {"gunTrailID", RosettaType::Int, "gunTrailID", "11"},
    {"nEngines", RosettaType::Int, "nEngines", "1"},
    {"engine1Location", RosettaType::Vector, "engineLocation[0]", "0 0 0"},
    {"engine2Location", RosettaType::Vector, "engineLocation[1]", "0 0 0"},
    {"engine3Location", RosettaType::Vector, "engineLocation[2]", "0 0 0"},
    {"engine4Location", RosettaType::Vector, "engineLocation[3]", "0 0 0"},
    {"engine5Location", RosettaType::Vector, "engineLocation[4]", "0 0 0"},
    {"engine6Location", RosettaType::Vector, "engineLocation[5]", "0 0 0"},
    {"engine7Location", RosettaType::Vector, "engineLocation[6]", "0 0 0"},
    {"engine8Location", RosettaType::Vector, "engineLocation[7]", "0 0 0"},
    {"engineSmokes", RosettaType::Int, "engineSmokes", "0"},
    {"wingTipLocation", RosettaType::Vector, "wingTipLocation", "0 0 0"},
    {"vortex1Location", RosettaType::Vector, "vortex1Location", "0 0 0"},
    {"vortex2Location", RosettaType::Vector, "vortex2Location", "0 0 0"},
    {"vortexPS1Location", RosettaType::Vector, "vortexPS1Location", "0 0 0"},
    {"vortexPS2Location", RosettaType::Vector, "vortexPS2Location", "0 0 0"},
    {"vortexPS3Location", RosettaType::Vector, "vortexPS3Location", "0 0 0"},
    {"largeVortex", RosettaType::Int, "largeVortex", "0"},
    {"vortexAOALimit", RosettaType::Vector, "vortexAOALimit", "29.5"},
    {"refuelLocation", RosettaType::Vector, "refuelLocation", "0 0 0"},
    {"hardpoint1Grp", RosettaType::Int, "hardpointrg[0]", "-1"},
    {"hardpoint2Grp", RosettaType::Int, "hardpointrg[1]", "-1"},
    {"hardpoint3Grp", RosettaType::Int, "hardpointrg[2]", "-1"},
    {"hardpoint4Grp", RosettaType::Int, "hardpointrg[3]", "-1"},
    {"hardpoint5Grp", RosettaType::Int, "hardpointrg[4]", "-1"},
    {"hardpoint6Grp", RosettaType::Int, "hardpointrg[5]", "-1"},
    {"hardpoint7Grp", RosettaType::Int, "hardpointrg[6]", "-1"},
    {"hardpoint8Grp", RosettaType::Int, "hardpointrg[7]", "-1"},
    {"hardpoint9Grp", RosettaType::Int, "hardpointrg[8]", "-1"},
    {"hardpoint10Grp", RosettaType::Int, "hardpointrg[9]", "-1"},
    {"hardpoint11Grp", RosettaType::Int, "hardpointrg[10]", "-1"},
    {"hardpoint12Grp", RosettaType::Int, "hardpointrg[11]", "-1"},
    {"hardpoint13Grp", RosettaType::Int, "hardpointrg[12]", "-1"},
    {"hardpoint14Grp", RosettaType::Int, "hardpointrg[13]", "-1"},
    {"hardpoint15Grp", RosettaType::Int, "hardpointrg[14]", "-1"},
    {"hardpoint16Grp", RosettaType::Int, "hardpointrg[15]", "-1"},
    {"hp1SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[0]", "-1 -1 0"},
    {"hp2SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[1]", "-1 -1 0"},
    {"hp3SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[2]", "-1 -1 0"},
    {"hp4SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[3]", "-1 -1 0"},
    {"hp5SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[4]", "-1 -1 0"},
    {"hp6SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[5]", "-1 -1 0"},
    {"hp7SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[6]", "-1 -1 0"},
    {"hp8SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[7]", "-1 -1 0"},
    {"hp9SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[8]", "-1 -1 0"},
    {"hp10SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[9]", "-1 -1 0"},
    {"hp11SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[10]", "-1 -1 0"},
    {"hp12SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[11]", "-1 -1 0"},
    {"hp13SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[12]", "-1 -1 0"},
    {"hp14SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[13]", "-1 -1 0"},
    {"hp15SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[14]", "-1 -1 0"},
    {"hp16SwitchDofRate", RosettaType::Vector, "hpSwitchDofRate[15]", "-1 -1 0"},
    {"gunSwitchDofRate", RosettaType::LookupTable, "gunSwitchDofRate", "-1 -1 0"},
    {"sndExt", RosettaType::Int, "sndExt", "35"},
    {"sndWind", RosettaType::Int, "sndWind", "33"},
    {"sndAbInt", RosettaType::Int, "sndAbInt", "40"},
    {"sndAbExt", RosettaType::Int, "sndAbExt", "39"},
    {"sndEject", RosettaType::Int, "sndEject", "5"},
    {"sndSpdBrakeStart", RosettaType::Int, "sndSpdBrakeStart", "141"},
    {"sndSpdBrakeLoop", RosettaType::Int, "sndSpdBrakeLoop", "140"},
    {"sndSpdBrakeEnd", RosettaType::Int, "sndSpdBrakeEnd", "139"},
    {"sndSpdBrakeWind", RosettaType::Int, "sndSpdBrakeWind", "142"},
    {"sndOverSpeed1", RosettaType::Int, "sndOverSpeed1", "191"},
    {"sndOverSpeed2", RosettaType::Int, "sndOverSpeed2", "192"},
    {"sndGunStart", RosettaType::Int, "sndGunStart", "25"},
    {"sndGunLoop", RosettaType::Int, "sndGunLoop", "26"},
    {"sndGunEnd", RosettaType::Int, "sndGunEnd", "27"},
    {"sndBBPullup", RosettaType::Int, "sndBBPullup", "68"},
    {"sndBBBingo", RosettaType::Int, "sndBBBingo", "66"},
    {"sndBBWarning", RosettaType::Int, "sndBBWarning", "63"},
    {"sndBBCaution", RosettaType::Int, "sndBBCaution", "64"},
    {"sndBBChaffFlareLow", RosettaType::Int, "sndBBChaffFlareLow", "184"},
    {"sndBBFlare", RosettaType::Int, "sndBBFlare", "138"},
    {"sndBBChaffFlare", RosettaType::Int, "sndBBChaffFlare", "183"},
    {"sndBBChaffFlareOut", RosettaType::Int, "sndBBChaffFlareOut", "185"},
    {"sndBBAltitude", RosettaType::Int, "sndBBAltitude", "65"},
    {"sndBBLock", RosettaType::Int, "sndBBLock", "67"},
    {"sndTouchDown", RosettaType::Int, "sndTouchDown", "42"},
    {"sndWheelBrakes", RosettaType::Int, "sndWheelBrakes", "132"},
    {"sndDragChute", RosettaType::Int, "sndDragChute", "217"},
    {"sndLowSpeed", RosettaType::Int, "sndLowSpeed", "167"},
    {"sndFlapStart", RosettaType::Int, "sndFlapStart", "145"},
    {"sndFlapLoop", RosettaType::Int, "sndFlapLoop", "144"},
    {"sndFlapEnd", RosettaType::Int, "sndFlapEnd", "143"},
    {"sndHookStart", RosettaType::Int, "sndHookStart", "195"},
    {"sndHookLoop", RosettaType::Int, "sndHookLoop", "194"},
    {"sndHookEnd", RosettaType::Int, "sndHookEnd", "193"},
    {"sndGearCloseStart", RosettaType::Int, "sndGearCloseStart", "147"},
    {"sndGearCloseEnd", RosettaType::Int, "sndGearCloseEnd", "146"},
    {"sndGearOpenStart", RosettaType::Int, "sndGearOpenStart", "149"},
    {"sndGearOpenEnd", RosettaType::Int, "sndGearOpenEnd", "150"},
    {"sndGearLoop", RosettaType::Int, "sndGearLoop", "148"},
    {"sndCanopyOpenStart", RosettaType::Int, "sndCanopyOpenStart", "271"},
    {"sndCanopyOpenEnd", RosettaType::Int, "sndCanopyOpenEnd", "272"},
    {"sndCanopyCloseStart", RosettaType::Int, "sndCanopyCloseStart", "273"},
    {"sndCanopyCloseEnd", RosettaType::Int, "sndCanopyCloseEnd", "274"},
    {"sndCanopyLoop", RosettaType::Int, "sndCanopyLoop", "275"},
    {"rollLimitForAiInWP", RosettaType::Float, "rollLimitForAiInWP", "180.0"},
    {"flap2Nozzle", RosettaType::Int, "flap2Nozzle", "0"},
    {"startGroundAvoidCheck", RosettaType::Float, "startGroundAvoidCheck", "3000.0"},
    {"limitPstick", RosettaType::Int, "limitPstick", "1"},
    {"refuelSpeed", RosettaType::Float, "refuelSpeed", "310.0"},
    {"refuelAltitude", RosettaType::Float, "refuelAltitude", "22500.0"},
    {"decelDistance", RosettaType::Float, "decelDistance", "1000.0"},
    {"followRate", RosettaType::Float, "followRate", "20.0"},
    {"desiredClosureFactor", RosettaType::Float, "desiredClosureFactor", "0.25"},
    {"IL78Factor", RosettaType::Float, "IL78Factor", "0.0"},
    {"longLeg", RosettaType::Float, "longLeg", "100.0"},
    {"shortLeg", RosettaType::Float, "shortLeg", "25.0"},
    {"refuelRate", RosettaType::Float, "refuelRate", "50.0"},
    {"AIBoomDistance", RosettaType::Float, "AIBoomDistance", "50.0"},
    {"nBooms", RosettaType::Int, "numBooms", "1"},
    {"BoomRFPos", RosettaType::Vector, "BoomRFPos", "0 0 0"},
    {"BoomStoredAngle", RosettaType::Float, "BoomStoredAngle", "14"},
    {"nDrogues", RosettaType::Int, "numDrogues", "0"},
    {"activeDrogue", RosettaType::Int, "activeDrogue", "1"},
    {"DrogueExt", RosettaType::Float, "DrogueExt", "40"},
    {"DrogueRFPos", RosettaType::Vector, "DrogueRFPos", "-60 0 0"},
    {"boomParent", RosettaType::Int, "boomParent", "2211"},
    {"drogueParent", RosettaType::Int, "drogueParent", "2221"},
    {"refuelBoomSlot0", RosettaType::Int, "refuelBoomSlot", "0"},
    {"refuelDrogueSlot0", RosettaType::Int, "refuelDrogueSlot[0]", "0"},
    {"refuelDrogueSlot1", RosettaType::Int, "refuelDrogueSlot[1]", "1"},
    {"refuelDrogueSlot2", RosettaType::Int, "refuelDrogueSlot[2]", "2"},
    {"tankerType", RosettaType::Int, "tankerType", "6"},
    {"BingoReturnDistance", RosettaType::Float, "BingoReturnDistance", "0.0"},
    {"jokerFactor", RosettaType::Float, "jokerFactor", "2.0"},
    {"bingoFactor", RosettaType::Float, "bingoFactor", "5.0"},
    {"fumesFactor", RosettaType::Float, "fumesFactor", "15.0"},
    {"maxRippleCount", RosettaType::Int, "maxRippleCount", "19"},
    {"largePark", RosettaType::Int, "largePark", "0"},
    {"HtsAble", RosettaType::Int, "HtsAble", "0"},
    {"Has_TFR", RosettaType::Int, "Has_TFR", "0"},
    {"PID_K", RosettaType::Float, "PID_K", "0.5"},
    {"PID_KI", RosettaType::Float, "PID_KI", "0.0"},
    {"PID_KD", RosettaType::Float, "PID_KD", "0.39"},
    {"TFR_LimitMX", RosettaType::Int, "TFR_LimitMX", "0"},
    {"TFR_Corner", RosettaType::Float, "TFR_Corner", "350.0"},
    {"TFR_Gain", RosettaType::Float, "TFR_Gain", "0.010"},
    {"EVA_Gain", RosettaType::Float, "EVA_Gain", "5.0"},
    {"TFR_MaxRoll", RosettaType::Float, "TFR_MaxRoll", "20.0"},
    {"TFR_SoftG", RosettaType::Float, "TFR_SoftG", "2.0"},
    {"TFR_MedG", RosettaType::Float, "TFR_MedG", "4.0"},
    {"TFR_HardG", RosettaType::Float, "TFR_HardG", "6.0"},
    {"TFR_Clearance", RosettaType::Float, "TFR_Clearance", "20.0"},
    {"SlowPercent", RosettaType::Float, "SlowPercent", "0.0"},
    {"TFR_lookAhead", RosettaType::Float, "TFR_lookAhead", "4000.0"},
    {"EVA1_SoftFactor", RosettaType::Float, "EVA1_SoftFactor", "0.6"},
    {"EVA2_SoftFactor", RosettaType::Float, "EVA2_SoftFactor", "0.4"},
    {"EVA1_MedFactor", RosettaType::Float, "EVA1_MedFactor", "0.8"},
    {"EVA2_MedFactor", RosettaType::Float, "EVA2_MedFactor", "0.6"},
    {"EVA1_HardFactor", RosettaType::Float, "EVA1_HardFactor", "1.2"},
    {"EVA2_HardFactor", RosettaType::Float, "EVA2_HardFactor", "0.9"},
    {"TFR_GammaCorrMult", RosettaType::Float, "TFR_GammaCorrMult", "1.0"},
    {"LantirnCameraX", RosettaType::Float, "LantirnCameraX", "10.0"},
    {"LantirnCameraY", RosettaType::Float, "LantirnCameraY", "2.0"},
    {"LantirnCameraZ", RosettaType::Float, "LantirnCameraZ", "5.0"},
    {"MinTGTMAR", RosettaType::Float, "minTGTMAR", "0.0"},
    {"MaxMARIdedStart", RosettaType::Float, "maxMARIdedStart", "0.0"},
    {"AddMARIded5k", RosettaType::Float, "addMARIded5k", "0.0"},
    {"AddMARIded18k", RosettaType::Float, "addMARIded18k", "0.0"},
    {"AddMARIded28k", RosettaType::Float, "addMARIded28k", "0.0"},
    {"AddMARIdedSpike", RosettaType::Float, "addMARIdedSpike", "0.0"},
    {"animEngineRPMMult", RosettaType::Float, "animEngineRPMMult", "1000.0"},
    {"animSpoiler1Max", RosettaType::Float, "animSpoiler1Max", "0.0"},
    {"animSpoiler1Rate", RosettaType::Float, "animSpoiler1Rate", "45.0"},
    {"animSpoiler1OffAtWingSweep", RosettaType::Float, "animSpoiler1OffAtWingSweep", "70.0"},
    {"animSpoiler1AirBrake", RosettaType::Int, "animSpoiler1AirBrake", "1"},
    {"animSpoiler2Max", RosettaType::Float, "animSpoiler2Max", "0.0"},
    {"animSpoiler2Rate", RosettaType::Float, "animSpoiler2Rate", "20.0"},
    {"animSpoiler2OffAtWingSweep", RosettaType::Float, "animSpoiler2OffAtWingSweep", "45.0"},
    {"animSpoiler2AirBrake", RosettaType::Int, "animSpoiler2AirBrake", "1"},
    {"animExhNozIdle", RosettaType::Float, "animExhNozIdle", "0.0"},
    {"animExhNozMil", RosettaType::Float, "animExhNozMil", "10.0"},
    {"animExhNozAB", RosettaType::Float, "animExhNozAB", "0.0"},
    {"animExhNozRate", RosettaType::Float, "animExhNozRate", "5.0"},
    {"animStrobeOnTime", RosettaType::Float, "animStrobeOnTime", "0.08"},
    {"animStrobeOffTime", RosettaType::Float, "animStrobeOffTime", "2.0"},
    {"animWingFlashOnTime", RosettaType::Float, "animWingFlashOnTime", "0.4"},
    {"animWingFlashOffTime", RosettaType::Float, "animWingFlashOffTime", "0.5"},
    {"animHookAngle", RosettaType::Float, "animHookAngle", "60.0"},
    {"animHookRate", RosettaType::Float, "animHookRate", "10.0"},
    {"animThrRevAngle", RosettaType::Float, "animThrRevAngle", "60.0"},
    {"animThrRevRate", RosettaType::Float, "animThrRevRate", "10.0"},
    {"catapultThrustMultiplier", RosettaType::Float, "catapultThrustMultiplier", "4.0"},
    {"maxLasingAlt", RosettaType::Float, "maxLasingAlt", "25000.0"},
    {"hasProgrammableEWS", RosettaType::Int, "hasProgrammableEWS", "1"},
    {"dataLinkCapLevel", RosettaType::Int, "dataLinkCapLevel", "1"},
    {"animWingFoldAngle", RosettaType::Float, "animWingFoldAngle", "110.0"},
    {"animWingFoldRate", RosettaType::Float, "animWingFoldRate", "5.0"},
    {"animAileronRate", RosettaType::Float, "animAileronRate", "45.0"},
    {"animSwingWingStages", RosettaType::Int, "animSwingWingStages", "2"},
    {"animSwingWingMach1", RosettaType::Float, "animSwingWingMach[0]", "0.6"},
    {"animSwingWingMach2", RosettaType::Float, "animSwingWingMach[1]", "0.8"},
    {"animSwingWingMach3", RosettaType::Float, "animSwingWingMach[2]", "0.0"},
    {"animSwingWingMach4", RosettaType::Float, "animSwingWingMach[3]", "0.0"},
    {"animSwingWingMach5", RosettaType::Float, "animSwingWingMach[4]", "0.0"},
    {"animSwingWingMach6", RosettaType::Float, "animSwingWingMach[5]", "0.0"},
    {"animSwingWingMach7", RosettaType::Float, "animSwingWingMach[6]", "0.0"},
    {"animSwingWingMach8", RosettaType::Float, "animSwingWingMach[7]", "0.0"},
    {"animSwingWingMach9", RosettaType::Float, "animSwingWingMach[8]", "0.0"},
    {"animSwingWingMach10", RosettaType::Float, "animSwingWingMach[9]", "0.0"},
    {"animSwingWingAngle1", RosettaType::Float, "animSwingWingAngle[0]", "25.0"},
    {"animSwingWingAngle2", RosettaType::Float, "animSwingWingAngle[1]", "50.0"},
    {"animSwingWingAngle3", RosettaType::Float, "animSwingWingAngle[2]", "0.0"},
    {"animSwingWingAngle4", RosettaType::Float, "animSwingWingAngle[3]", "0.0"},
    {"animSwingWingAngle5", RosettaType::Float, "animSwingWingAngle[4]", "0.0"},
    {"animSwingWingAngle6", RosettaType::Float, "animSwingWingAngle[5]", "0.0"},
    {"animSwingWingAngle7", RosettaType::Float, "animSwingWingAngle[6]", "0.0"},
    {"animSwingWingAngle8", RosettaType::Float, "animSwingWingAngle[7]", "0.0"},
    {"animSwingWingAngle9", RosettaType::Float, "animSwingWingAngle[8]", "0.0"},
    {"animSwingWingAngle10", RosettaType::Float, "animSwingWingAngle[9]", "0.0"},
    {"animSwingWingRate", RosettaType::Float, "animSwingWingRate", "5.0"},
    {"animWheelRadius1", RosettaType::Float, "animWheelRadius[0]", "0.0"},
    {"animWheelRadius2", RosettaType::Float, "animWheelRadius[1]", "0.0"},
    {"animWheelRadius3", RosettaType::Float, "animWheelRadius[2]", "0.0"},
    {"animWheelRadius4", RosettaType::Float, "animWheelRadius[3]", "0.0"},
    {"animWheelRadius5", RosettaType::Float, "animWheelRadius[4]", "0.0"},
    {"animWheelRadius6", RosettaType::Float, "animWheelRadius[5]", "0.0"},
    {"animWheelRadius7", RosettaType::Float, "animWheelRadius[6]", "0.0"},
    {"animWheelRadius8", RosettaType::Float, "animWheelRadius[7]", "0.0"},
    {"animRefuelAngle", RosettaType::Float, "animRefuelAngle", "1.0"},
    {"animRefuelRate", RosettaType::Float, "animRefuelRate", ".5"},
    {"fuelGaugeMultiplier", RosettaType::Float, "fuelGaugeMultiplier", "10"},
    {"animGearMaxComp1", RosettaType::Float, "animGearMaxComp[0]", "0.0"},
    {"animGearMaxComp2", RosettaType::Float, "animGearMaxComp[1]", "0.0"},
    {"animGearMaxComp3", RosettaType::Float, "animGearMaxComp[2]", "0.0"},
    {"animGearMaxComp4", RosettaType::Float, "animGearMaxComp[3]", "0.0"},
    {"animGearMaxComp5", RosettaType::Float, "animGearMaxComp[4]", "0.0"},
    {"animGearMaxComp6", RosettaType::Float, "animGearMaxComp[5]", "0.0"},
    {"animGearMaxComp7", RosettaType::Float, "animGearMaxComp[6]", "0.0"},
    {"animGearMaxComp8", RosettaType::Float, "animGearMaxComp[7]", "0.0"},
    {"animGearMaxExt1", RosettaType::Float, "animGearMaxExt[0]", "0.0"},
    {"animGearMaxExt2", RosettaType::Float, "animGearMaxExt[1]", "0.0"},
    {"animGearMaxExt3", RosettaType::Float, "animGearMaxExt[2]", "0.0"},
    {"animGearMaxExt4", RosettaType::Float, "animGearMaxExt[3]", "0.0"},
    {"animGearMaxExt5", RosettaType::Float, "animGearMaxExt[4]", "0.0"},
    {"animGearMaxExt6", RosettaType::Float, "animGearMaxExt[5]", "0.0"},
    {"animGearMaxExt7", RosettaType::Float, "animGearMaxExt[6]", "0.0"},
    {"animGearMaxExt8", RosettaType::Float, "animGearMaxExt[7]", "0.0"},
    {"sndExternalVol", RosettaType::Float, "sndExternalVol", "-2000.0"},
    {"sndInt", RosettaType::Int, "sndInt", "-1"},
    {"sndIntChart", RosettaType::LookupTable, "sndIntChart", "1  0 1"},
    {"sndAbIntChart", RosettaType::LookupTable, "sndAbIntChart", "2  0 0  1 1"},
    {"sndInt2Chart", RosettaType::LookupTable, "sndInt2Chart", "3  0 0  1 1  1.035 1"},
    {"sndExtChart", RosettaType::LookupTable, "sndExtChart", "1  0 1"},
    {"sndAbExtChart", RosettaType::LookupTable, "sndAbExtChart", "2  0 0  1 1"},
    {"sndExt2Chart", RosettaType::LookupTable, "sndExt2Chart", "3  0 0  1 1  1.035 1"},
    {"sndIntPitchChart", RosettaType::LookupTable, "sndIntPitchChart", "2 0 0 1.03 1.47"},
    {"sndAbIntPitchChart", RosettaType::LookupTable, "sndAbIntPitchChart", "2 0 0 1.03 1.47"},
    {"sndInt2PitchChart", RosettaType::LookupTable, "sndInt2PitchChart", "2 0 0 1.03 1.47"},
    {"sndExtPitchChart", RosettaType::LookupTable, "sndExtPitchChart", "2 0 0 1.03 1.47"},
    {"sndAbExtPitchChart", RosettaType::LookupTable, "sndAbExtPitchChart", "2 0 0 1.03 1.47"},
    {"sndExt2PitchChart", RosettaType::LookupTable, "sndExt2PitchChart", "2 0 0 1.03 1.47"},
    {"sndInt2", RosettaType::Int, "sndInt2", "0"},
    {"sndExt2", RosettaType::Int, "sndExt2", "0"},
    {"sndAero1", RosettaType::Int, "sndAero[0]", "0"},
    {"sndAero2", RosettaType::Int, "sndAero[1]", "0"},
    {"sndAero3", RosettaType::Int, "sndAero[2]", "0"},
    {"sndAero4", RosettaType::Int, "sndAero[3]", "0"},
    {"sndAero1AOAChart", RosettaType::LookupTable, "sndAeroAOAChart[0]", "1 0 0"},
    {"sndAero2AOAChart", RosettaType::LookupTable, "sndAeroAOAChart[1]", "1 0 0"},
    {"sndAero3AOAChart", RosettaType::LookupTable, "sndAeroAOAChart[2]", "1 0 0"},
    {"sndAero4AOAChart", RosettaType::LookupTable, "sndAeroAOAChart[3]", "1 0 0"},
    {"sndAero1SpeedChart", RosettaType::LookupTable, "sndAeroSpeedChart[0]", "1 0 0"},
    {"sndAero2SpeedChart", RosettaType::LookupTable, "sndAeroSpeedChart[1]", "1 0 0"},
    {"sndAero3SpeedChart", RosettaType::LookupTable, "sndAeroSpeedChart[2]", "1 0 0"},
    {"sndAero4SpeedChart", RosettaType::LookupTable, "sndAeroSpeedChart[3]", "1 0 0"},
    {"FlarePos1", RosettaType::Vector, "Flare.Pos[0]", "0 0 0"},
    {"FlareVec1", RosettaType::Vector, "Flare.Vec[0]", "0 0 200"},
    {"FlareCount1", RosettaType::Int, "Flare.Decoys[0]", "30"},
    {"FlarePos2", RosettaType::Vector, "Flare.Pos[1]", "0 0 0"},
    {"FlareVec2", RosettaType::Vector, "Flare.Vec[1]", "0 0 200"},
    {"FlareCount2", RosettaType::Int, "Flare.Decoys[1]", "30"},
    {"FlarePos3", RosettaType::Vector, "Flare.Pos[2]", "0 0 0"},
    {"FlareVec3", RosettaType::Vector, "Flare.Vec[2]", "0 0 200"},
    {"FlareCount3", RosettaType::Int, "Flare.Decoys[2]", "30"},
    {"FlarePos4", RosettaType::Vector, "Flare.Pos[3]", "0 0 0"},
    {"FlareVec4", RosettaType::Vector, "Flare.Vec[3]", "0 0,200"},
    {"FlareCount4", RosettaType::Int, "Flare.Decoys[3]", "30"},
    {"FlarePos5", RosettaType::Vector, "Flare.Pos[4]", "0 0 0"},
    {"FlareVec5", RosettaType::Vector, "Flare.Vec[4]", "0 0 200"},
    {"FlareCount5", RosettaType::Int, "Flare.Decoys[4]", "30"},
    {"FlarePos6", RosettaType::Vector, "Flare.Pos[5]", "0 0 0"},
    {"FlareVec6", RosettaType::Vector, "Flare.Vec[5]", "0 0 200"},
    {"FlareCount6", RosettaType::Int, "Flare.Decoys[5]", "30"},
    {"FlarePos7", RosettaType::Vector, "Flare.Pos[6]", "0 0 0"},
    {"FlareVec7", RosettaType::Vector, "Flare.Vec[6]", "0 0 200"},
    {"FlareCount7", RosettaType::Int, "Flare.Decoys[6]", "30"},
    {"FlarePos8", RosettaType::Vector, "Flare.Pos[7]", "0 0 0"},
    {"FlareVec8", RosettaType::Vector, "Flare.Vec[7]", "0 0 200"},
    {"FlareCount8", RosettaType::Int, "Flare.Decoys[7]", "30"},
    {"FlarePos9", RosettaType::Vector, "Flare.Pos[8]", "0 0 0"},
    {"FlareVec9", RosettaType::Vector, "Flare.Vec[8]", "0 0 200"},
    {"FlareCount9", RosettaType::Int, "Flare.Decoys[8]", "30"},
    {"FlarePos10", RosettaType::Vector, "Flare.Pos[9]", "0 0 0"},
    {"FlareVec10", RosettaType::Vector, "Flare.Vec[9]", "0 0 200"},
    {"FlareCount10", RosettaType::Int, "Flare.Decoys[9]", "30"},
    {"FlareSeq", RosettaType::Int, "Flare.Sequence", "0"},
    {"FlareDispensers", RosettaType::Int, "Flare.Count", "1"},
    {"ChaffPos1", RosettaType::Vector, "Chaff.Pos[0]", "0 0 0"},
    {"ChaffVec1", RosettaType::Vector, "Chaff.Vec[0]", "0 0 200"},
    {"ChaffCount1", RosettaType::Int, "Chaff.Decoys[0]", "30"},
    {"ChaffPos2", RosettaType::Vector, "Chaff.Pos[1]", "0 0 0"},
    {"ChaffVec2", RosettaType::Vector, "Chaff.Vec[1]", "0 0 200"},
    {"ChaffCount2", RosettaType::Int, "Chaff.Decoys[1]", "30"},
    {"ChaffPos3", RosettaType::Vector, "Chaff.Pos[2]", "0 0 0"},
    {"ChaffVec3", RosettaType::Vector, "Chaff.Vec[2]", "0 0 200"},
    {"ChaffCount3", RosettaType::Int, "Chaff.Decoys[2]", "30"},
    {"ChaffPos4", RosettaType::Vector, "Chaff.Pos[3]", "0 0 0"},
    {"ChaffVec4", RosettaType::Vector, "Chaff.Vec[3]", "0 0 200"},
    {"ChaffCount4", RosettaType::Int, "Chaff.Decoys[3]", "30"},
    {"ChaffPos5", RosettaType::Vector, "Chaff.Pos[4]", "0 0 0"},
    {"ChaffVec5", RosettaType::Vector, "Chaff.Vec[4]", "0 0 200"},
    {"ChaffCount5", RosettaType::Int, "Chaff.Decoys[4]", "30"},
    {"ChaffPos6", RosettaType::Vector, "Chaff.Pos[5]", "0 0 0"},
    {"ChaffVec6", RosettaType::Vector, "Chaff.Vec[5]", "0 0 200"},
    {"ChaffCount6", RosettaType::Int, "Chaff.Decoys[5]", "30"},
    {"ChaffPos7", RosettaType::Vector, "Chaff.Pos[6]", "0 0 0"},
    {"ChaffVec7", RosettaType::Vector, "Chaff.Vec[6]", "0 0 200"},
    {"ChaffCount7", RosettaType::Int, "Chaff.Decoys[6]", "30"},
    {"ChaffPos8", RosettaType::Vector, "Chaff.Pos[7]", "0 0 0"},
    {"ChaffVec8", RosettaType::Vector, "Chaff.Vec[7]", "0 0 200"},
    {"ChaffCount8", RosettaType::Int, "Chaff.Decoys[7]", "30"},
    {"ChaffPos9", RosettaType::Vector, "Chaff.Pos[8]", "0 0 0"},
    {"ChaffVec9", RosettaType::Vector, "Chaff.Vec[8]", "0 0 200"},
    {"ChaffCount9", RosettaType::Int, "Chaff.Decoys[8]", "30"},
    {"ChaffPos10", RosettaType::Vector, "Chaff.Pos[9]", "0 0 0"},
    {"ChaffVec10", RosettaType::Vector, "Chaff.Vec[9]", "0 0 200"},
    {"ChaffCount10", RosettaType::Int, "Chaff.Decoys[9]", "30"},
    {"ChaffSeq", RosettaType::Int, "Chaff.Sequence", "0"},
    {"ChaffDispensers", RosettaType::Int, "Chaff.Count", "1"},
    {"PilotEyePos", RosettaType::Vector, "pilotEyePos", "15 0 -3"},
    {"typeAC", RosettaType::Int, "typeAC", "0"},
    {"typeEngine", RosettaType::Int, "typeEngine", "0"},
    {"elevRate", RosettaType::Float, "elevRate", "90"},
    {"gunPitch", RosettaType::Float, "gunElevation", "0"},
    {"gunYaw", RosettaType::Float, "gunAzimuth", "0"},
    {"MeanTimeBetweenFailures", RosettaType::Float, "MeanTimeBetweenFailures", "0"},
    {"anim", RosettaType::Float, "anim", "0.0"},
    {"A2GJDAMAlt", RosettaType::Float, "A2GJDAMAlt", "20000.0"},
    {"A2GJSOWAlt", RosettaType::Float, "A2GJSOWAlt", "25000.0"},
    {"A2GHarmAlt", RosettaType::Float, "A2GHarmAlt", "20000.0"},
    {"A2GAGMAlt", RosettaType::Float, "A2GAGMAlt", "18000.0"},
    {"A2GGBUAlt", RosettaType::Float, "A2GGBUAlt", "18000.0"},
    {"A2GDumbHDAlt", RosettaType::Float, "A2GDumbHDAlt", "1500.0"},
    {"A2GClusterAlt", RosettaType::Float, "A2GClusterAlt", "15000.0"},
    {"A2GDumbLDAlt", RosettaType::Float, "A2GDumbLDAlt", "15000.0"},
    {"A2GGenericBombAlt", RosettaType::Float, "A2GGenericBombAlt", "1000.0"},
    {"A2GGunRocketAlt", RosettaType::Float, "A2GGunRocketAlt", "8000.0"},
    {"A2GCameraAlt", RosettaType::Float, "A2GCameraAlt", "12000.0"},
    {"A2GBombMissileAlt", RosettaType::Float, "A2GBombMissileAlt", "13000.0"},
    {"swingwingHinge", RosettaType::Vector, "swingWingHinge", "2 3 0"},
    {"animIntakeRamp1", RosettaType::TwoDTable, "animIntakeRamp[0]", "0 0"},
    {"animIntakeRamp2", RosettaType::TwoDTable, "animIntakeRamp[1]", "0 0"},
    {"animIntakeRamp3", RosettaType::TwoDTable, "animIntakeRamp[2]", "0 0"},
    {"FTITStart", RosettaType::Float, "FTITStart", "5.0"},
    {"FTITIdle", RosettaType::Float, "FTITIdle", "7.0"},
    {"FTITMax", RosettaType::Float, "FTITMax", "8.9"},
    {"criticalAOA", RosettaType::Float, "criticalAOA", "0.0"},
    {"hasIFF", RosettaType::Int, "hasIFF", "0"},
    {"hasThrRev", RosettaType::Int, "hasThrRev", "0"},
};

const RosettaEntry* findAuxAeroEntry(const std::string& key) {
    for (std::size_t i = 0; i < kAuxAeroRosettaCount; ++i) {
        if (key == kAuxAeroRosetta[i].key) return &kAuxAeroRosetta[i];
    }
    return nullptr;
}

} // namespace f4::data
