#!/usr/bin/env python3
"""Reconstruct kc10.json's complete auxAero record.

kc10.dat is the one fleet .dat file not committed as a test fixture (the
original bulk conversion predates the fixture set), so its record cannot be
regenerated by dat2json the way the other 24 aircraft are. What IS committed
is kc10.json's typed `aux` view — produced from the real kc10.dat by the
then-current converter — which carries the overrides the flight model
consumes (hasLef/hasTef=0, jfsSpoolRates, lef/tef rates, rudderMaxAngle,
typeEngine, ...).

Rule (documented in CHANGES.md, Task 72): the record is the rosetta schema
defaults, then every rosetta key with a typed-view counterpart takes the
typed view's value expressed in legacy units. The result is consistent with
kc10.json's own typed view by construction; keys without a typed counterpart
(aero/engine/geometry tables excepted) carry FreeFalcon's readin.cpp default.

Run from the repo root:  python3 scripts/reconstruct_kc10_auxaero.py
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ROSETTA = REPO / "f4-convert" / "rosetta" / "auxaero_field_map.json"
KC10 = REPO / "Data" / "Aircraft" / "kc10.json"

# typed `aux` block key -> rosetta record key (spelling differences only)
ALIASES = {
    "tefTakeOff": "tefTakeoff",
    "elevatorRolls": "elevatorRoll",
}

# typed keys that are NOT AuxAeroData keys (no record counterpart)
NON_RECORD = set()


STRTOD_RE = re.compile(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")


def strtod(tok):
    """C strtod semantics: parse the leading number, else 0.0 ('0,200' -> 0)."""
    m = STRTOD_RE.match(tok)
    return float(m.group(0)) if m else 0.0


def rosetta_default(entry):
    """Mirror completeAuxAeroRecord's default parse (strtod + zero-fill)."""
    toks = entry["default"].split()
    t = entry["type"]
    if t == "ID_FLOAT":
        return strtod(toks[0]) if toks else 0.0
    if t == "ID_INT":
        return int(strtod(toks[0])) if toks else 0
    if t == "ID_VECTOR":
        vals = [strtod(x) for x in toks[:3]]
        return (vals + [0.0, 0.0, 0.0])[:3]
    return [strtod(x) for x in toks]  # charts / tables


def typed_value(aux, aux_key, entry):
    v = aux[aux_key]
    t = entry["type"]
    if t == "ID_INT":
        if isinstance(v, bool):
            return int(v)
        return int(v)
    if t == "ID_VECTOR":
        return [float(x) for x in v]
    if t in ("ID_LOOKUPTABLE", "ID_2DTABLE"):
        if isinstance(v, list):
            return [float(x) for x in v]
        return [float(v)]
    return float(v)


def main() -> int:
    ros = json.loads(ROSETTA.read_text())
    keys = ros["keys"]
    kc = json.loads(KC10.read_text())
    aux = kc["aux"]

    # Build the typed-view lookup: rosetta record key -> (aux key, value).
    typed = {}
    for aux_key, v in aux.items():
        rec_key = ALIASES.get(aux_key, aux_key)
        if rec_key in keys:
            typed[rec_key] = (aux_key, v)

    rec = {}
    taken_from_typed = []
    for key, entry in keys.items():
        if key in typed:
            aux_key, v = typed[key]
            rec[key] = typed_value(aux, aux_key, entry)
            taken_from_typed.append(key)
        else:
            rec[key] = rosetta_default(entry)

    kc["auxAero"] = rec
    # Match the converter's nlohmann dump(2) conventions: sorted keys, no
    # trailing newline.
    KC10.write_text(json.dumps(kc, indent=2, sort_keys=True))
    print(f"kc10.json auxAero: {len(rec)} keys "
          f"({len(taken_from_typed)} from the typed view, "
          f"{len(rec) - len(taken_from_typed)} schema defaults)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
