// test_flight_model.cpp — integration tests for the full flight model.
//
// These tests load real aircraft configurations (from the JSON fixtures
// generated by f4-convert) and exercise the full pipeline:
//   - init() with a real config
//   - trim() to find a 1-G level flight condition
//   - 60-second stability run (no pilot input, should stay roughly level)
//   - FCS step response (pitch stick input produces G)
//
// The tests verify that the flight model produces physically reasonable
// behavior: no NaNs, altitude stays roughly constant in level flight,
// G load responds to stick input, etc.

#include "f4/flight/flight_model.hpp"
#include "f4/data/config_loader.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <filesystem>
#include <vector>

using namespace f4::flight;
using f4::math::Vec3d;

namespace {

constexpr const char* kFixturesDir = F4_GENERATED_FIXTURES_DIR;

bool fixturesExist() {
    return std::filesystem::exists(kFixturesDir);
}

/// Load the f16 config from the generated fixtures.
bool loadF16Config(f4::data::AircraftConfig& cfg) {
    if (!fixturesExist()) return false;
    const std::string path = std::string(kFixturesDir) + "/f16.json";
    if (!std::filesystem::exists(path)) return false;
    auto result = f4::data::loadConfig(path);
    if (!result.ok) return false;
    cfg = result.config;
    return true;
}

}  // namespace

// ============================================================================
// init() with a real aircraft config
// ============================================================================

TEST(FlightModelTest, InitWithF16Config) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP() << "f16.json fixture not found";

    FlightModel fm;
    EXPECT_NO_THROW(fm.init(cfg, 10000.0, 500.0, 0.0, true));
    EXPECT_NEAR(fm.state().kin.vt, 500.0, 1e-6);
    EXPECT_NEAR(-fm.state().kin.z, 10000.0, 1e-6);  // altitude = -z
    EXPECT_GT(fm.state().qbar, 0.0);
    EXPECT_GT(fm.state().mach, 0.0);
}

TEST(FlightModelTest, InitThrowsOnEmptyConfig) {
    f4::data::AircraftConfig cfg;  // empty
    FlightModel fm;
    EXPECT_THROW(fm.init(cfg, 10000.0, 500.0, 0.0, true), std::runtime_error);
}

// ============================================================================
// trim() converges for the f16
// ============================================================================

TEST(FlightModelTest, TrimConvergesForF16) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);

    bool converged = fm.trim();
    EXPECT_TRUE(converged) << "Trim did not converge";

    // After trim, nzcgs should be close to 1.0
    EXPECT_NEAR(fm.state().loads.nzcgs, 1.0, 0.1);
}

// ============================================================================
// 60-second stability run: trimmed, no input, should stay roughly level
// ============================================================================

TEST(FlightModelTest, SixtySecondStabilityRun) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm.trim());

    // Run 60 seconds at 60 Hz (dt = 1/60).
    // The primary check is that the simulation remains stable (no NaNs,
    // no divergence) for a full minute. Altitude/speed will drift because
    // we don't save the trim throttle — the test verifies stability, not
    // exact trim holding.
    const double dt = 1.0 / 60.0;
    PilotInput input;
    input.throttle = 0.5;  // moderate power

    const Vec3d groundNormal{0.0, 0.0, -1.0};
    const double groundZ = 0.0;

    for (int frame = 0; frame < 60 * 60; ++frame) {
        fm.update(dt, input, groundZ, groundNormal);
    }

    // After 60 seconds — the critical checks:
    // - No NaNs (the simulation didn't diverge)
    EXPECT_TRUE(std::isfinite(fm.state().kin.z));
    EXPECT_TRUE(std::isfinite(fm.state().kin.vt));
    EXPECT_TRUE(std::isfinite(fm.state().loads.nzcgs));
    EXPECT_TRUE(std::isfinite(fm.state().aero.alpha_deg));
    EXPECT_TRUE(std::isfinite(fm.state().engine.rpm));

    // - Alpha should be within the aircraft's limits (no stall/spin divergence)
    EXPECT_GT(fm.state().aero.alpha_deg, cfg.geometry.aoaMin_deg - 5.0);
    EXPECT_LT(fm.state().aero.alpha_deg, cfg.geometry.aoaMax_deg + 5.0);

    // - G load should be reasonable (not extreme)
    EXPECT_NEAR(fm.state().loads.nzcgs, 1.0, 3.0);

    // - RPM should be in a valid range
    EXPECT_GT(fm.state().engine.rpm, 0.0);
    EXPECT_LT(fm.state().engine.rpm, 2.0);
}

// ============================================================================
// FCS step response: pitch stick input produces G
// ============================================================================

TEST(FlightModelTest, PitchStickChangesAlpha) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm.trim());

    const double trimAlpha = fm.state().aero.alpha_deg;

    // Apply half back stick for 2 seconds
    PilotInput input;
    input.throttle = 0.5;
    input.pstick = 0.5;  // half back stick
    const double dt = 1.0 / 60.0;
    const Vec3d groundNormal{0.0, 0.0, -1.0};

    for (int frame = 0; frame < 120; ++frame) {
        fm.update(dt, input, 0.0, groundNormal);
    }

    // The FCS should respond to pitch input by changing alpha.
    // The exact direction depends on the FCS mode (G-command vs AOA-command)
    // and gain computation, but alpha should move away from trim.
    double finalAlpha = fm.state().aero.alpha_deg;
    EXPECT_GT(std::fabs(finalAlpha - trimAlpha), 0.1)
        << "Alpha did not change after pitch input: trim=" << trimAlpha
        << " final=" << finalAlpha;
}

// ============================================================================
// Throttle response: more throttle -> more speed
// ============================================================================

TEST(FlightModelTest, ThrottleIncreasesSpeed) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm.trim());

    const double initialVt = fm.state().kin.vt;

    // Apply full throttle for 10 seconds
    PilotInput input;
    input.throttle = 1.5;  // full AB
    const double dt = 1.0 / 60.0;
    const Vec3d groundNormal{0.0, 0.0, -1.0};

    for (int frame = 0; frame < 600; ++frame) {
        fm.update(dt, input, 0.0, groundNormal);
    }

    // Speed should have increased
    EXPECT_GT(fm.state().kin.vt, initialVt);
}

// ============================================================================
// Ground operations: aircraft stays on the ground when spawned on ground
// ============================================================================

TEST(FlightModelTest, GroundSpawnStaysOnGround) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 0.0, 10.0, 0.0, false);  // on ground, 10 ft/s

    // Run 5 seconds with no input
    PilotInput input;
    const double dt = 1.0 / 60.0;
    const Vec3d groundNormal{0.0, 0.0, -1.0};

    for (int frame = 0; frame < 300; ++frame) {
        fm.update(dt, input, 0.0, groundNormal);
    }

    // Should still be on the ground (not airborne)
    EXPECT_FALSE(fm.state().gear.inAir);
    // Z should be at or above the ground (z <= 0 in NED)
    EXPECT_LE(fm.state().kin.z, 0.0);
}

// ============================================================================
// Multiple aircraft configs load and run without crashing
// ============================================================================

TEST(FlightModelTest, MultipleAircraftInitAndRun) {
    if (!fixturesExist()) GTEST_SKIP();

    // Test a representative sample of aircraft types
    const std::vector<std::string> aircraft = {
        "f16.json", "f15.json", "a10.json", "b52.json",
        "c130.json", "mig29.json", "Su27.json"
    };

    for (const auto& name : aircraft) {
        const std::string path = std::string(kFixturesDir) + "/" + name;
        if (!std::filesystem::exists(path)) continue;

        auto result = f4::data::loadConfig(path);
        ASSERT_TRUE(result.ok) << "Failed to load " << name;

        FlightModel fm;
        ASSERT_NO_THROW(fm.init(result.config, 10000.0, 500.0, 0.0, true))
            << "init failed for " << name;

        // Run 1 second
        PilotInput input;
        input.throttle = 0.5;
        const double dt = 1.0 / 60.0;
        const Vec3d groundNormal{0.0, 0.0, -1.0};

        for (int frame = 0; frame < 60; ++frame) {
            fm.update(dt, input, 0.0, groundNormal);
        }

        // No NaNs
        EXPECT_TRUE(std::isfinite(fm.state().kin.z))
            << "NaN in z for " << name;
        EXPECT_TRUE(std::isfinite(fm.state().kin.vt))
            << "NaN in vt for " << name;
    }
}
