// test_flight_model.cpp — integration tests for the full flight model.
//
// These tests load real aircraft configurations (from the JSON fixtures
// generated by f4-convert) and exercise the full pipeline:
//   - init() with a real config
//   - trim() to find a 1-G level flight condition
//   - 60-second stability run (no pilot input, should stay roughly level)
//   - FCS step response (pitch stick input produces G)
//
// The tests verify that the flight model produces physically reasonable
// behavior: no NaNs, altitude stays roughly constant in level flight,
// G load responds to stick input, etc.

#include "f4/flight/flight_model.hpp"
#include "f4/data/config_loader.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <filesystem>
#include <vector>

using namespace f4::flight;
using f4::math::Vec3d;

namespace {

constexpr const char* kFixturesDir = F4_GENERATED_FIXTURES_DIR;

bool fixturesExist() {
    return std::filesystem::exists(kFixturesDir);
}

/// Load the f16 config from the generated fixtures.
bool loadF16Config(f4::data::AircraftConfig& cfg) {
    if (!fixturesExist()) return false;
    const std::string path = std::string(kFixturesDir) + "/f16.json";
    if (!std::filesystem::exists(path)) return false;
    auto result = f4::data::loadConfig(path);
    if (!result.ok) return false;
    cfg = result.config;
    return true;
}

}  // namespace

// ============================================================================
// init() with a real aircraft config
// ============================================================================

TEST(FlightModelTest, InitWithF16Config) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP() << "f16.json fixture not found";

    FlightModel fm;
    EXPECT_NO_THROW(fm.init(cfg, 10000.0, 500.0, 0.0, true));
    EXPECT_NEAR(fm.state().kin.vt, 500.0, 1e-6);
    EXPECT_NEAR(-fm.state().kin.z, 10000.0, 1e-6);  // altitude = -z
    EXPECT_GT(fm.state().qbar, 0.0);
    EXPECT_GT(fm.state().mach, 0.0);
}

TEST(FlightModelTest, InitThrowsOnEmptyConfig) {
    f4::data::AircraftConfig cfg;  // empty
    FlightModel fm;
    EXPECT_THROW(fm.init(cfg, 10000.0, 500.0, 0.0, true), std::runtime_error);
}

// ============================================================================
// trim() converges for the f16
// ============================================================================

TEST(FlightModelTest, TrimConvergesForF16) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);

    bool converged = fm.trim();
    EXPECT_TRUE(converged) << "Trim did not converge";

    // After trim, nzcgs should be close to 1.0
    EXPECT_NEAR(fm.state().loads.nzcgs, 1.0, 0.1);
}

// ============================================================================
// 60-second stability run: trimmed, no input, should stay roughly level
// ============================================================================

TEST(FlightModelTest, SixtySecondStabilityRun) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm.trim());

    // Record the trim state so we can measure drift.
    const double initialAlt_ft = -fm.state().kin.z;       // altitude = -z
    const double initialVt_fps = fm.state().kin.vt;
    const double initialNz     = fm.state().loads.nzcgs;

    // Run 60 seconds at 60 Hz (dt = 1/60).
    // The primary check is that the simulation remains stable (no NaNs,
    // no divergence) for a full minute. Altitude/speed will drift because
    // we don't save the trim throttle — the test verifies stability, not
    // exact trim holding.
    const double dt = 1.0 / 60.0;
    PilotInput input;
    input.throttle = 0.5;  // moderate power

    const Vec3d groundNormal{0.0, 0.0, -1.0};
    const double groundZ = 0.0;

    for (int frame = 0; frame < 60 * 60; ++frame) {
        fm.update(dt, input, groundZ, groundNormal);
    }

    // After 60 seconds — the critical checks:
    // - No NaNs (the simulation didn't diverge)
    EXPECT_TRUE(std::isfinite(fm.state().kin.z));
    EXPECT_TRUE(std::isfinite(fm.state().kin.vt));
    EXPECT_TRUE(std::isfinite(fm.state().loads.nzcgs));
    EXPECT_TRUE(std::isfinite(to_degrees(fm.state().aero.alpha)));
    EXPECT_TRUE(std::isfinite(fm.state().engine.rpm));

    // - Alpha should be within the aircraft's limits (no stall/spin divergence)
    EXPECT_GT(to_degrees(fm.state().aero.alpha), cfg.geometry.aoaMin_deg - 5.0);
    EXPECT_LT(to_degrees(fm.state().aero.alpha), cfg.geometry.aoaMax_deg + 5.0);

    // - G load should remain near 1G. The previous 3-G tolerance was wide
    // enough to admit a fully-developed stall (0 G) or a 4-G pull (steady
    // level flight with no pilot input cannot legitimately exceed ~1.5 G
    // even with throttle drift). Tighten to ±1.0 G — still loose enough to
    // absorb transient pitch oscillations, but tight enough to catch a
    // diverging pitch loop.
    EXPECT_NEAR(fm.state().loads.nzcgs, 1.0, 1.0)
        << "initialNz=" << initialNz;

    // - Altitude drift bound. With 0.5 throttle (not the trim throttle)
    // the aircraft will drift because trim() does not seed the FCS
    // integrator — the FCS re-converges to a slightly different alpha in
    // the first few seconds, producing a slow descent or climb. The bound
    // below is intentionally loose: 12000 ft drift in 60 s still rejects
    // divergent EOMs (which hit 100000+ ft in seconds) while admitting
    // the known FCS-vs-trim settling transient. Tightening this requires
    // fixing the trim() → FCS integrator seeding, which is tracked as a
    // separate flight-model task.
    const double finalAlt_ft = -fm.state().kin.z;
    EXPECT_LT(std::fabs(finalAlt_ft - initialAlt_ft), 12000.0)
        << "initialAlt=" << initialAlt_ft << " finalAlt=" << finalAlt_ft;

    // - RPM should be in a valid range. Idle ~60%, mil ~100%, AB >100%.
    // A divergent engine model would hit 0 or negative RPM, or exceed 200%.
    EXPECT_GT(fm.state().engine.rpm, 0.0);
    EXPECT_LT(fm.state().engine.rpm, 2.0);

    // - Speed should not diverge. A stable sim may accelerate (0.5 throttle
    // is mid-power) but a 10x speed change in 60 s indicates divergence.
    EXPECT_LT(fm.state().kin.vt, initialVt_fps * 10.0);
    EXPECT_GT(fm.state().kin.vt, initialVt_fps * 0.1);
}

// ============================================================================
// FCS step response: pitch stick input produces G
// ============================================================================

TEST(FlightModelTest, PitchStickChangesAlpha) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm.trim());

    const double trimAlpha = to_degrees(fm.state().aero.alpha);
    const double trimNz    = fm.state().loads.nzcgs;

    // Run 2 s with NO stick input first — establishes the post-trim baseline
    // the FCS actually settles to (trim() does not seed the FCS integrator,
    // so the first few seconds after trim() involve some settling as the
    // FCS re-converges). This baseline is what we compare the stick-input
    // case against, so the test isolates the FCS response to the stick
    // input rather than measuring trim() + FCS-settling transient.
    PilotInput no_input;
    no_input.throttle = 0.5;
    const double dt = 1.0 / 60.0;
    const Vec3d groundNormal{0.0, 0.0, -1.0};
    for (int frame = 0; frame < 120; ++frame) {
        fm.update(dt, no_input, 0.0, groundNormal);
    }
    const double baselineAlpha = to_degrees(fm.state().aero.alpha);
    const double baselineNz    = fm.state().loads.nzcgs;

    // Re-init to the same trim condition, then apply half back stick for 2 s.
    FlightModel fm2;
    fm2.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm2.trim());

    PilotInput input;
    input.throttle = 0.5;
    input.pstick = 0.5;  // half back stick (nose-up)
    for (int frame = 0; frame < 120; ++frame) {
        fm2.update(dt, input, 0.0, groundNormal);
    }

    const double finalAlpha = to_degrees(fm2.state().aero.alpha);
    const double finalNz    = fm2.state().loads.nzcgs;

    // Alpha must be HIGHER than the no-input baseline (nose-up stick
    // commands more lift, which requires more alpha at constant speed).
    EXPECT_GT(finalAlpha - baselineAlpha, 0.5)
        << "Alpha did not increase above baseline after positive pitch "
        << "input: trim=" << trimAlpha << " baseline=" << baselineAlpha
        << " final=" << finalAlpha;

    // Nz must be HIGHER than the no-input baseline (positive stick commands
    // positive G). The 0.2 G lower bound is conservative — a half-stick
    // pull at 500 ft/s produces ~0.3-0.5 G above baseline in the current
    // FCS tuning — but it's still tight enough to catch a regressed pitch
    // path (e.g. pstick sign flipped, G limiter always active).
    EXPECT_GT(finalNz - baselineNz, 0.2)
        << "Nz did not increase above baseline after positive pitch input: "
        << "trimNz=" << trimNz << " baselineNz=" << baselineNz
        << " finalNz=" << finalNz;
}

// ============================================================================
// Throttle response: more throttle -> more speed
// ============================================================================

TEST(FlightModelTest, ThrottleIncreasesSpeed) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 10000.0, 500.0, 0.0, true);
    ASSERT_TRUE(fm.trim());

    const double initialVt = fm.state().kin.vt;

    // Apply full throttle (1.5 = full afterburner in the F-16's normalized
    // throttle convention: 0..1 = idle..mil, 1..2 = mil..full AB) for 10 s.
    PilotInput input;
    input.throttle = 1.5;  // full AB
    const double dt = 1.0 / 60.0;
    const Vec3d groundNormal{0.0, 0.0, -1.0};

    for (int frame = 0; frame < 600; ++frame) {
        fm.update(dt, input, 0.0, groundNormal);
    }

    const double finalVt = fm.state().kin.vt;
    const double deltaVt = finalVt - initialVt;  // ft/s gained

    // Speed must increase (full AB must always accelerate, never decelerate).
    EXPECT_GT(deltaVt, 0.0)
        << "Full AB did not increase speed: initial=" << initialVt
        << " final=" << finalVt;

    // Quantitative lower bound: a clean F-16 at 10000 ft / 500 ft/s under
    // full afterburner for 10 s should gain at least 50 ft/s (about 30 kt).
    // This is conservative — the real aircraft gains ~100-150 ft/s in 10 s
    // under AB — but it's tight enough to catch a regressed throttle path
    // (e.g. AB not lighting, throttle reversed, thrust table not loading).
    EXPECT_GT(deltaVt, 50.0)
        << "Full AB acceleration too small: initial=" << initialVt
        << " final=" << finalVt << " delta=" << deltaVt << " ft/s";
}

// ============================================================================
// Ground operations: aircraft stays on the ground when spawned on ground
// ============================================================================

TEST(FlightModelTest, GroundSpawnStaysOnGround) {
    f4::data::AircraftConfig cfg;
    if (!loadF16Config(cfg)) GTEST_SKIP();

    FlightModel fm;
    fm.init(cfg, 0.0, 10.0, 0.0, false);  // on ground, 10 ft/s

    // Run 5 seconds with no input
    PilotInput input;
    const double dt = 1.0 / 60.0;
    const Vec3d groundNormal{0.0, 0.0, -1.0};

    for (int frame = 0; frame < 300; ++frame) {
        fm.update(dt, input, 0.0, groundNormal);
    }

    // Should still be on the ground (not airborne)
    EXPECT_FALSE(fm.state().gear.inAir);
    // Z should be at or above the ground (z <= 0 in NED)
    EXPECT_LE(fm.state().kin.z, 0.0);
}

// ============================================================================
// Multiple aircraft configs load and run without crashing
// ============================================================================

TEST(FlightModelTest, MultipleAircraftInitAndRun) {
    if (!fixturesExist()) GTEST_SKIP();

    // Test a representative sample of aircraft types
    const std::vector<std::string> aircraft = {
        "f16.json", "f15.json", "a10.json", "b52.json",
        "c130.json", "mig29.json", "Su27.json"
    };

    for (const auto& name : aircraft) {
        const std::string path = std::string(kFixturesDir) + "/" + name;
        if (!std::filesystem::exists(path)) continue;

        auto result = f4::data::loadConfig(path);
        ASSERT_TRUE(result.ok) << "Failed to load " << name;

        FlightModel fm;
        ASSERT_NO_THROW(fm.init(result.config, 10000.0, 500.0, 0.0, true))
            << "init failed for " << name;

        // Run 1 second
        PilotInput input;
        input.throttle = 0.5;
        const double dt = 1.0 / 60.0;
        const Vec3d groundNormal{0.0, 0.0, -1.0};

        for (int frame = 0; frame < 60; ++frame) {
            fm.update(dt, input, 0.0, groundNormal);
        }

        // No NaNs
        EXPECT_TRUE(std::isfinite(fm.state().kin.z))
            << "NaN in z for " << name;
        EXPECT_TRUE(std::isfinite(fm.state().kin.vt))
            << "NaN in vt for " << name;
    }
}
